# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minkowskiDimCalculator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MinkowskiDimCalculatorDialogBase(object):
    def setupUi(self, MinkowskiDimCalculatorDialogBase):
        MinkowskiDimCalculatorDialogBase.setObjectName("MinkowskiDimCalculatorDialogBase")
        MinkowskiDimCalculatorDialogBase.resize(345, 362)
        self.gridLayout = QtWidgets.QGridLayout(MinkowskiDimCalculatorDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(MinkowskiDimCalculatorDialogBase)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(MinkowskiDimCalculatorDialogBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.onlySelectedFeaturesCheckBox = QtWidgets.QCheckBox(MinkowskiDimCalculatorDialogBase)
        self.onlySelectedFeaturesCheckBox.setObjectName("onlySelectedFeaturesCheckBox")
        self.gridLayout.addWidget(self.onlySelectedFeaturesCheckBox, 1, 0, 1, 4)
        self.tabWidget = QtWidgets.QTabWidget(MinkowskiDimCalculatorDialogBase)
        self.tabWidget.setObjectName("tabWidget")
        self.layerGridTab = QtWidgets.QWidget()
        self.layerGridTab.setObjectName("layerGridTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layerGridTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layerGridGroupBox = QtWidgets.QGroupBox(self.layerGridTab)
        self.layerGridGroupBox.setObjectName("layerGridGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layerGridGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layerGridAttributeNameLineEdit = QtWidgets.QLineEdit(self.layerGridGroupBox)
        self.layerGridAttributeNameLineEdit.setObjectName("layerGridAttributeNameLineEdit")
        self.gridLayout_2.addWidget(self.layerGridAttributeNameLineEdit, 1, 1, 1, 1)
        self.layerGridNumberOfStepsSpinBox = QtWidgets.QSpinBox(self.layerGridGroupBox)
        self.layerGridNumberOfStepsSpinBox.setMaximum(999999999)
        self.layerGridNumberOfStepsSpinBox.setProperty("value", 10)
        self.layerGridNumberOfStepsSpinBox.setObjectName("layerGridNumberOfStepsSpinBox")
        self.gridLayout_2.addWidget(self.layerGridNumberOfStepsSpinBox, 4, 1, 1, 1)
        self.layerGridAutoButton = QtWidgets.QPushButton(self.layerGridGroupBox)
        self.layerGridAutoButton.setObjectName("layerGridAutoButton")
        self.gridLayout_2.addWidget(self.layerGridAutoButton, 5, 0, 1, 1)
        self.layerGridStartSizeLineEdit = QtWidgets.QLineEdit(self.layerGridGroupBox)
        self.layerGridStartSizeLineEdit.setObjectName("layerGridStartSizeLineEdit")
        self.gridLayout_2.addWidget(self.layerGridStartSizeLineEdit, 2, 1, 1, 1)
        self.layerGridEndSizeLineEdit = QtWidgets.QLineEdit(self.layerGridGroupBox)
        self.layerGridEndSizeLineEdit.setObjectName("layerGridEndSizeLineEdit")
        self.gridLayout_2.addWidget(self.layerGridEndSizeLineEdit, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layerGridGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layerGridGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layerGridGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layerGridGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.layerGridGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.layerGridTab, "")
        self.featureGridTab = QtWidgets.QWidget()
        self.featureGridTab.setObjectName("featureGridTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.featureGridTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.featureGridGroupBox = QtWidgets.QGroupBox(self.featureGridTab)
        self.featureGridGroupBox.setObjectName("featureGridGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.featureGridGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.featureGridGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.featureGridAttributeNameLineEdit = QtWidgets.QLineEdit(self.featureGridGroupBox)
        self.featureGridAttributeNameLineEdit.setObjectName("featureGridAttributeNameLineEdit")
        self.gridLayout_4.addWidget(self.featureGridAttributeNameLineEdit, 0, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.featureGridGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.featureGridAutoCheckBox = QtWidgets.QCheckBox(self.featureGridGroupBox)
        self.featureGridAutoCheckBox.setObjectName("featureGridAutoCheckBox")
        self.gridLayout_4.addWidget(self.featureGridAutoCheckBox, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.featureGridGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.featureGridGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.featureGridStartSizeComboBox = QgsFieldComboBox(self.featureGridGroupBox)
        self.featureGridStartSizeComboBox.setObjectName("featureGridStartSizeComboBox")
        self.gridLayout_4.addWidget(self.featureGridStartSizeComboBox, 1, 2, 1, 1)
        self.featureGridEndSizeComboBox = QgsFieldComboBox(self.featureGridGroupBox)
        self.featureGridEndSizeComboBox.setObjectName("featureGridEndSizeComboBox")
        self.gridLayout_4.addWidget(self.featureGridEndSizeComboBox, 2, 2, 1, 1)
        self.featureGridNumberOfStepsComboBox = QgsFieldComboBox(self.featureGridGroupBox)
        self.featureGridNumberOfStepsComboBox.setObjectName("featureGridNumberOfStepsComboBox")
        self.gridLayout_4.addWidget(self.featureGridNumberOfStepsComboBox, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.featureGridGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.featureGridTab, "")
        self.gridLayout.addWidget(self.tabWidget, 4, 0, 1, 5)
        self.cancelButton = QtWidgets.QPushButton(MinkowskiDimCalculatorDialogBase)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 5, 3, 1, 1)
        self.runButton = QtWidgets.QPushButton(MinkowskiDimCalculatorDialogBase)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 5, 4, 1, 1)
        self.layerComboBox = QgsMapLayerComboBox(MinkowskiDimCalculatorDialogBase)
        self.layerComboBox.setObjectName("layerComboBox")
        self.gridLayout.addWidget(self.layerComboBox, 0, 1, 1, 4)
        self.label_6 = QtWidgets.QLabel(MinkowskiDimCalculatorDialogBase)
        self.label_6.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 5)
        self.helpLink = QtWidgets.QLabel(MinkowskiDimCalculatorDialogBase)
        self.helpLink.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLink.setOpenExternalLinks(True)
        self.helpLink.setObjectName("helpLink")
        self.gridLayout.addWidget(self.helpLink, 5, 2, 1, 1)

        self.retranslateUi(MinkowskiDimCalculatorDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MinkowskiDimCalculatorDialogBase)

    def retranslateUi(self, MinkowskiDimCalculatorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MinkowskiDimCalculatorDialogBase.setWindowTitle(_translate("MinkowskiDimCalculatorDialogBase", "Minkowski Dimension Calculator"))
        self.label.setText(_translate("MinkowskiDimCalculatorDialogBase", "Layer (Linestring):"))
        self.onlySelectedFeaturesCheckBox.setText(_translate("MinkowskiDimCalculatorDialogBase", "Only for selected features"))
        self.layerGridGroupBox.setTitle(_translate("MinkowskiDimCalculatorDialogBase", "Settings"))
        self.layerGridAttributeNameLineEdit.setToolTip(_translate("MinkowskiDimCalculatorDialogBase", "Name of field that will be created or recalculated for vector layer"))
        self.layerGridAttributeNameLineEdit.setText(_translate("MinkowskiDimCalculatorDialogBase", "mink_dem"))
        self.layerGridNumberOfStepsSpinBox.setToolTip(_translate("MinkowskiDimCalculatorDialogBase", "This is how much grids will be calculated"))
        self.layerGridAutoButton.setText(_translate("MinkowskiDimCalculatorDialogBase", "Auto"))
        self.layerGridStartSizeLineEdit.setToolTip(_translate("MinkowskiDimCalculatorDialogBase", "Size of cell at first step. The biggest one. You can choose it based on extent - 4 or 5 cells in a row is good start"))
        self.layerGridEndSizeLineEdit.setToolTip(_translate("MinkowskiDimCalculatorDialogBase", "Size of cell on last step. The smallest one. For maximal accurace it can be near smallest distance between feature\'s nodes. For reason of optimization can be larger, depending on scale of your research"))
        self.label_2.setText(_translate("MinkowskiDimCalculatorDialogBase", "Attribute name"))
        self.label_5.setText(_translate("MinkowskiDimCalculatorDialogBase", "Number of steps"))
        self.label_3.setText(_translate("MinkowskiDimCalculatorDialogBase", "Start cell size"))
        self.label_4.setText(_translate("MinkowskiDimCalculatorDialogBase", "End cell size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.layerGridTab), _translate("MinkowskiDimCalculatorDialogBase", "Layer grid"))
        self.featureGridGroupBox.setTitle(_translate("MinkowskiDimCalculatorDialogBase", "Settings"))
        self.label_7.setText(_translate("MinkowskiDimCalculatorDialogBase", "Attribute name"))
        self.featureGridAttributeNameLineEdit.setToolTip(_translate("MinkowskiDimCalculatorDialogBase", "Name of field that will be created or recalculated for vector layer"))
        self.featureGridAttributeNameLineEdit.setText(_translate("MinkowskiDimCalculatorDialogBase", "mink_dem"))
        self.label_8.setText(_translate("MinkowskiDimCalculatorDialogBase", "Start cell size"))
        self.featureGridAutoCheckBox.setText(_translate("MinkowskiDimCalculatorDialogBase", "Auto"))
        self.label_9.setText(_translate("MinkowskiDimCalculatorDialogBase", "End cell size"))
        self.label_10.setText(_translate("MinkowskiDimCalculatorDialogBase", "Number of steps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.featureGridTab), _translate("MinkowskiDimCalculatorDialogBase", "Feature grid"))
        self.cancelButton.setText(_translate("MinkowskiDimCalculatorDialogBase", "Cancel"))
        self.runButton.setText(_translate("MinkowskiDimCalculatorDialogBase", "Run"))
        self.label_6.setText(_translate("MinkowskiDimCalculatorDialogBase", "Use \"Layer grid\" mode if features in your layer are comparable in size and MD could be calculated with common grid. Otherwise, use \"Feature grid\". Auto-settings are OK for current layer objects comparison, but for real absolute values better to use manual settings."))
        self.helpLink.setText(_translate("MinkowskiDimCalculatorDialogBase", "<a href=\"http://www.ekazakov.info/projects/mdc_tutorial.html\">Help</a>"))

from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox
